config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root 'tops#index'

  get 'terms_of_service', to: 'terms_of_service#show'
  get 'privacy_policy', to: 'privacy_policy#show'

  # システム管理者用画面
  namespace :admin, path: 'aaaaaaaa' do
    root to: 'schools#index', as: 'root'

    devise_for :admins,
               only: %i[session password],
               controllers: { passwords: 'admins/passwords',
                              sessions: 'admins/sessions' }
    resources :schools do
      resources :teachers, param: :code, only: %i[show new create edit update]
    end
  end

  #++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
  # マルチテナントの切り分け
  scope '/:school_code' do
    #++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    # 教師用画面
    namespace :teacher, path: 't' do
      root to: 'students#index', as: 'root'

      devise_for :teachers,
                 only: %i[session password],
                 controllers: { passwords: 'teachers/passwords',
                                sessions: 'teachers/sessions' }
                                
      resources :students, only: %i[index edit update show destroy]
      resources :test_results, only: %i[index edit update show destroy] do
        collection do
          get :subject_achievement_rate
        end
      end
    end

    # 生徒用画面
    scope module: :student do
      root to: 'test_results#index', as: 'student_root'

      devise_for :students,
                 only: %i[session password registration confirmation],
                 controllers: { passwords: 'students/passwords',
                                sessions: 'students/sessions',
                                registrations: 'students/registrations',
                                confirmations: 'students/confirmations' }
      resources :test_results, except: [:show] do
        collection do
          get :subject_achievement_rate
        end
      end
    end
  end
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  belongs_to :school
  validates :name, presence: true

  validates :login_id, uniqueness: true, presence: true
  validate :login_id_format

  def login_id_format
    unless login_id.match?(/\A(?=.*[0-9])(?=.*[a-zA-Z])[0-9a-zA-Z]+\z/)
      errors.add(:login_id, "は数字とアルファベットの両方を含む必要があります")
    end
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         authentication_keys: %i[login_id]

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["login_id = :value", { :value => login_id }]).first
    else
      where(conditions).first
    end
  end
      
  def email_required?
    false
  end
      
  def email_changed?
    false
  end

  def will_save_change_to_email?
    false
  end
end

app/models/test_result.rb
class TestResult < ApplicationRecord
  belongs_to :test_name
  belongs_to :max_score
  belongs_to :subject
  belongs_to :student

  before_save :calculate_achievement_rate

  validate :achievement_rate_within_range
  validates :score, presence: true
  validates :preparation_time_minutes, presence: true

  def display_preparation_time
    hours = preparation_time_minutes / 60
    minutes = preparation_time_minutes % 60
    "#{hours}時間#{minutes}分"
  end

  def self.achievement_rate_by_subject(subject)
    joins(:subject, :test_name)
      .where(subjects: { subject_name: subject })
      .pluck(:test_name, :achievement_rate)
  end

  def self.scatter_chart_data_by_subject(subject)
    joins(:subject)
      .where(subjects: { subject_name: subject })
      .pluck(:preparation_time_minutes, :achievement_rate)
  end

  private

  def calculate_achievement_rate
    return if score.nil? || max_score.nil?

    max_score_value = max_score.max_score
    self.achievement_rate = ((score.to_f / max_score_value) * 100).round
  end

  def achievement_rate_within_range
    if score.present? && max_score.present?
      calculated_achievement_rate = ((score.to_f / max_score.max_score) * 100).round
      if calculated_achievement_rate > 100
        errors.add(:score, "達成率は100%を超えることはできません")
      end
    end
  end

  def self.ransackable_attributes(auth_object = nil)
    ["achievement_rate", "created_at", "id", "id_value", "max_score_id", "preparation_time_minutes", "score", "student_id", "subject_id", "test_name_id", "updated_at"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["max_score", "student", "subject", "test_name"]
  end
end

app/controllers/admin/teachers_controller.rb
class Admin::TeachersController < Admin::BaseController
  before_action :set_school
  before_action :set_teacher, only: [:show, :edit, :update]

  # GET /schools/:school_id/teachers/new
  def new
    @teacher = @school.teachers.build
  end

  # POST /schools/:school_id/teachers
  def create
    @teacher = @school.teachers.build(teacher_params)
    if @teacher.save
      redirect_to admin_school_path(@school), success: t('defaults.message.created', item: Teacher.model_name.human)
    else
      flash.now['danger'] = t('defaults.message.not_created', item: Teacher.model_name.human)
      render :new, status: :unprocessable_entity
    end
  end

  def show
  end

  # GET /schools/:school_id/teachers/:id/edit
  def edit
  end

  # PATCH /schools/:school_id/teachers/:id
  def update
    if @teacher.update(teacher_params)
      redirect_to admin_school_teacher_path(@school, @teacher), success: t('defaults.message.updated', item: Teacher.model_name.human)
    else
      flash.now['danger'] = t('defaults.message.not_updated', item: Teacher.model_name.human)
      render :edit, status: :unprocessable_entity
    end
  end


  private
  # Use callbacks to share common setup or constraints between actions.
  def set_school
    @school = School.find(params[:school_id])
  end

  def set_teacher
    @teacher = @school.teachers.find(params[:code])
  end

  # Only allow a list of trusted parameters through.
  def teacher_params
    params.require(:teacher).permit(:login_id, :name, :email, :password, :password_confirmation)
  end
end

app/controllers/student/test_results_controller.rb
class Student::TestResultsController < Student::BaseController 

  before_action :find_test_result, only: [:edit, :update, :destroy]
  
  def index
    @q = current_student.test_results.ransack(params[:q])
    @test_results = @q.result.order(created_at: :desc).page(params[:page])
  end
  
  def new
    @test_result = TestResult.new
  end
  
  def create
    @test_result = current_student.test_results.build(test_result_params)
    if @test_result.save
      redirect_to test_results_path, success: t('defaults.message.created', item: TestResult.model_name.human)
    else
      flash.now['danger'] = t('defaults.message.not_created', item: TestResult.model_name.human)
      render :new, status: :unprocessable_entity
    end
  end
  
  def edit
    @test_result = current_student.test_results.find(params[:id])
  end
  
  def update
    @test_result = current_student.test_results.find(params[:id])
    if @test_result.update(test_result_params)
      redirect_to test_results_path, success: t('defaults.message.updated', item: TestResult.model_name.human)
    else
      flash.now['danger'] = t('defaults.message.not_updated', item: TestResult.model_name.human)
      render :edit
    end
  end
  
  def destroy
    @test_result = current_student.test_results.find(params[:id])
    @test_result.destroy!
    redirect_to test_results_path, success: t('defaults.message.deleted', item: TestResult.model_name.human)
  end
  
  def subject_achievement_rate
    @subjects = Subject.pluck(:subject_name)
    @data_by_subject = {}
    @subjects.each do |subject|
      @data_by_subject[subject] = {
        line_chart_data: current_student.test_results.achievement_rate_by_subject(subject).map.with_index { |(test_name, achievement_rate), index| ["#{test_name} (#{index + 1})", achievement_rate] },
        scatter_chart_data: current_student.test_results.scatter_chart_data_by_subject(subject)
      }
    end
  end
  
  private
  
  def find_test_result
    @test_result = current_student.test_results.find(params[:id])
  end
  
  def test_result_params
    params.require(:test_result).permit(:test_name_id, :score, :max_score_id, :preparation_time_minutes, :subject_id)
  end
end
  

app/controllers/teacher/base_controller.rb
class Teacher::BaseController < ApplicationController
  before_action :check_teacher
  layout 'teacher/layouts/application'

  private

  def not_authenticated
    flash[:warning] = t('defaults.message.require_login')
    redirect_to root_path
  end

  def check_teacher
    redirect_to new_teacher_teacher_session_path, warning: t('defaults.message.not_authorized') unless current_teacher_teacher
  end
end

app/controllers/teacher/students_controller.rb
class Teacher::StudentsController < Teacher::BaseController
  before_action :set_student, only: %i[edit update show destroy]
  
  def index
    @q = current_teacher_teacher.school.students.ransack(params[:q])
    @students = @q.result(distinct: true).order(created_at: :desc).page(params[:page])
  end


  def edit; end

  def update
    if @student.update(student_params)
      redirect_to teacher_student_path(@student), success: t('defaults.message.updated', item: Student.model_name.human)
    else
      flash.now['danger'] = t('defaults.message.not_updated', item: Student.model_name.human)
      render 'edit', status: :unprocessable_entity
    end
  end

  def show
    @average_achievement_rate = @student.average_achievement_rate
  end

  def destroy
    @student.destroy!
    redirect_to teacher_students_path, success: t('defaults.message.deleted', item: Student.model_name.human)
  end
  
  private

  def set_student
    @student = Student.find(params[:id])
  end
  
  def student_params
    params.require(:student).permit(:email, :password, :password_confirmation, :name, :grade_id, :student_class_id, :school_id )
  end
end

app/controllers/teacher/test_results_controller.rb
class Teacher::TestResultsController < Teacher::BaseController
  before_action :find_test_result, only: [:edit, :update, :show, :destroy]

  def index
    @students = current_teacher_teacher.school.students
    @q = TestResult.where(student_id: @students.pluck(:id)).ransack(params[:q])
    @test_results = @q.result(distinct: true).order(created_at: :desc).page(params[:page])
  end

  def edit; end

  def update
    if @test_result.update(test_result_params)
      redirect_to teacher_test_result_path(@test_result), success: t('defaults.message.updated', item: TestResult.model_name.human)
    else
      flash.now['danger'] = t('defaults.message.not_updated', item: TestResult.model_name.human)
      render :edit
    end
  end

  def show; end

  def destroy
    @test_result.destroy!
    redirect_to teacher_test_results_path, success: t('defaults.message.deleted', item: TestResult.model_name.human)
  end

  def subject_achievement_rate
    @student = Student.find(params[:id])
    @subjects = Subject.pluck(:subject_name)
    @data_by_subject = {}
    @subjects.each do |subject|
      @data_by_subject[subject] = {
        line_chart_data: @student.test_results.achievement_rate_by_subject(subject).map.with_index { |(test_name, achievement_rate), index| ["#{test_name} (#{index + 1})", achievement_rate] },
        scatter_chart_data: @student.test_results.scatter_chart_data_by_subject(subject)
      }
    end
  end

  private

  def find_test_result
    @test_result = TestResult.find(params[:id])
  end

  def test_result_params
    params.require(:test_result).permit(:test_name_id, :score, :max_score_id, :preparation_time_minutes, :subject_id)
  end
end

app/controllers/teachers/passwords_controller.rb
# frozen_string_literal: true

class Teachers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/teachers/sessions_controller.rb
# frozen_string_literal: true

class Teachers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  def destroy
    super
  end

  protected

  def after_sign_in_path_for(resource)
    teacher_root_path
  end

  def after_sign_out_path_for(resource_or_scope)
    new_teacher_teacher_session_path
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/views/teacher/test_results/_test_result.html.erb
<tr>
  <td>
    <%= link_to test_result.student.name, subject_achievement_rate_teacher_test_results_path(id: test_result.student.id) %>
  </td>
  <td>
    <%= test_result.student.grade.name %>
  </td>
  <td>
    <%= test_result.student.student_class.name %>
  </td>
  <td>
    <%= link_to TestName.find(test_result.test_name_id).test_name, teacher_test_result_path(id: test_result.id) %>
  </td>
  <td>
    <%= Subject.find(test_result.subject_id).subject_name %>
  </td>
  <td>
    <%= l test_result.created_at, format: :long %>
  </td>
  <td>
    <div class="btn-group" role="group">
      <%= link_to t('defaults.show'), teacher_test_result_path(id: test_result.id), class: 'btn btn-info me-2' %>
      <%= link_to t('defaults.edit'), edit_teacher_test_result_path(id: test_result.id), class: 'btn btn-success me-2' %>
      <%= button_to t('defaults.delete'), teacher_test_result_path(id: test_result.id), method: :delete, data: { turbo_confirm: "本当に削除しますか？" }, class: 'btn btn-danger' %>
    </div>  
  </td>
</tr>

app/views/teacher/test_results/edit.html.erb
<% content_for(:title, t('.title')) %>
<div class="container d-flex flex-wrap justify-content-center justify-content-center pt-5">
  <div class="w-100 align-self-end pt-1 pt-md-4 pb-4" style="max-width: 526px;">
    <h1 class="text-center text-xl-start"><h1><%= t('.title') %></h1></h1>
    <%= form_with model: @test_result, url: teacher_test_result_path(@test_result), local: true do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <div class="row">
        <div class="col-12 mb-4">
          <div class="position-relative mb-0">
            <div class="form-group">
              <%= f.label :test_name_id %>
              <%= f.collection_select :test_name_id, TestName.all, :id, :test_name, {}, {class: "form-control custom-select-lg"} %>
            </div>
          </div>
        </div>
        <div class="col-sm-6">
          <div class="position-relative mb-4">
            <div class="form-group">
              <%= f.label :max_score_id %>
            <%= f.collection_select :max_score_id, MaxScore.all, :id, :max_score, {}, {class: "form-control custom-select-lg"} %>
          </div>
          </div>
        </div>
        <div class="col-sm-6">
          <div class="position-relative mb-4">
            <div class="form-group">
              <%= f.label :score %>
              <%= f.number_field :score, class: 'form-control' %>
            </div>
          </div>
        </div>
        <div class="col-sm-6">
          <div class="position-relative mb-4">
            <div class="form-group">
              <%= f.label :subject_id %>
              <%= f.collection_select :subject_id, Subject.all, :id, :subject_name, {}, {class: "form-control custom-select-lg"} %>
            </div>
          </div>
        </div>
        <div class="col-sm-6">
          <div class="position-relative mb-4">
            <div class="form-group">
              <%= f.label :preparation_time_minutes %>
              <%= f.number_field :preparation_time_minutes, class: 'form-control' %>
            </div>
          </div>
        </div>
      </div>
      <%= f.submit class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/teacher/test_results/index.html.erb
<% content_for(:title, t('.title')) %>
<!-- Breadcrumb -->
<nav class="container mt-lg-4 pt-5" aria-label="breadcrumb"></nav>
<!-- Page content -->
<section class="container mt-4 mb-lg-5 pt-lg-2 pb-5">
  <!-- Page title + Layout switcher + Search form -->
  <div class="row align-items-end gy-3 mb-4 pb-lg-3 pb-1">
    <div class="col-lg-5 col-md-4">
      <h1 class="mb-2 mb-md-0"><%= t '.title' %></h1>
    </div>
    <div class="col-lg-7 col-md-8">
      <%= search_form_for @q, url: teacher_test_results_path do |f| %>
        <div class="row align-items-end">
          <div class="col-lg-2 col-md-6 col-sm-12 mb-2">
            <%= f.search_field :student_name_cont, class: 'form-control', placeholder: '氏名を検索' %>
          </div>
          <div class="col-lg-2 col-md-3 col-sm-6 mb-2">
            <%= f.select :student_grade_id_eq, Grade.all.map{|g| [g.name, g.id]}, { include_blank: '学年を検索' }, { class: 'form-select' } %>
          </div>
          <div class="col-lg-2 col-md-3 col-sm-6 mb-2">
            <%= f.select :student_student_class_id_eq, StudentClass.all.map{|c| [c.name, c.id]}, { include_blank: 'クラスを検索' }, { class: 'form-select' } %>
          </div>
          <div class="col-lg-2 col-md-4 col-sm-6 mb-2">
            <%= f.select :test_name_id_eq, TestName.all.map{|tn| [tn.test_name, tn.id]}, { include_blank: 'テスト名で検索' }, { class: 'form-select' } %>
          </div>
          <div class="col-lg-2 col-md-4 col-sm-6 mb-2">
            <%= f.select :subject_id_eq, Subject.all.map{|s| [s.subject_name, s.id]}, { include_blank: '教科名で検索' }, { class: 'form-select' } %>
          </div>
          <div class="col-lg-2 col-md-4 col-sm-6 mb-2">
            <%= f.submit "検索", class: 'btn btn-primary' %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12 mb-3">
      
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12">
      <table class="table table-striped">
        <thead>
        <tr>
          <th scope="col"><%= Student.human_attribute_name(:name) %></th>
          <th scope="col"><%= Student.human_attribute_name(:grade_id) %></th>
          <th scope="col"><%= Student.human_attribute_name(:student_class_id) %></th>
          <th scope="col"><%= TestResult.human_attribute_name(:test_name_id) %></th>
          <th scope="col"><%= TestResult.human_attribute_name(:subject_id) %></th>
          <th scope="col"><%= TestResult.human_attribute_name(:created_at) %></th>
          <th scope="col"></th>
        </tr>
        </thead>
        <tbody>
        <%= render @test_results %>
        </tbody>
      </table>
    </div>
  </div>
  <%= paginate @test_results %>
</section>

app/views/teacher/test_results/show.html.erb
<% content_for(:title, t('.title')) %>
<div class="container d-flex flex-wrap justify-content-center justify-content-center pt-5">
  <div class="w-100 align-self-end pt-1 pt-md-4 pb-4" style="max-width: 526px;">
    <h1><%= t('.title') %></h1>
    <div class="btn-group mb-3" role="group">
      <%= link_to t('defaults.edit'), edit_teacher_test_result_path(@test_result), class: 'btn btn-success me-2' %>
      <%= button_to t('defaults.delete'), teacher_test_result_path(@test_result), method: :delete, data: { turbo_confirm: "本当に削除しますか？" }, class: 'btn btn-danger me-2' %>
      <%= link_to 'テスト一覧に戻る', teacher_test_results_path, class: 'btn btn-primary' %>
    </div>
    <table class="table table-bordered bg-white">
      <tr>
        <th scope="row"><%= TestResult.human_attribute_name(:test_name) %></th>
        <td><%= TestName.find(@test_result.test_name_id).test_name %></td>
      </tr>
      <tr>
        <th scope="row"><%= TestResult.human_attribute_name(:subject_id) %></th>
        <td><%= Subject.find(@test_result.subject_id).subject_name %></td>
      </tr>
      <tr>
        <th scope="row"><%= Student.human_attribute_name(:name) %></th>
        <td><%= @test_result.student.name %></td>
      </tr>
      <tr>
        <th scope="row"><%= TestResult.human_attribute_name(:score) %></th>
        <td><%= @test_result.score %></td>
      </tr>
      <tr>
        <th scope="row"><%= TestResult.human_attribute_name(:max_score) %></th>
        <td><%= MaxScore.find(@test_result.max_score_id).max_score %></td>
      </tr>
      <tr>
        <th scope="row"><%= TestResult.human_attribute_name(:achievement_rate) %></th>
        <td><%= @test_result.achievement_rate %></td>
      </tr>
      <tr>
        <th scope="row"><%= TestResult.human_attribute_name(:display_preparation_time) %></th>
        <td><%= @test_result.display_preparation_time %></td>
      </tr>
      <tr>
        <th scope="row"><%= TestResult.human_attribute_name(:created_at) %></th>
        <td><%= l @test_result.created_at, format: :long %></td>
      </tr>
    </table>
  </div>
</div>

app/views/teacher/test_results/subject_achievement_rate.html.erb
<% content_for(:title, t('.title')) %>
<div class="container d-flex flex-wrap justify-content-center justify-content-center pt-5">
  <div class="w-100 align-self-end pt-1 pt-md-4 pb-4" style="max-width: 526px;">
    <h1><%= t '.title' %></h1>
  </div>
  
  <div class="w-100 align-self-end pt-1 pt-md-4 pb-4" style="max-width: 1000px;">
    <% @subjects.each do |subject| %>
      <div class="row">
        <div class="col-md-12">
          <h2><%= subject %>の結果</h2>
        </div>
        <% data = @data_by_subject[subject] %>
        <div class="col-md-6">
          <%= line_chart data[:line_chart_data], xtitle: 'テスト名', ytitle: '達成率 (%)', suffix: '%', height: '400px' %>
        </div>
        <div class="col-md-6">
          <%= scatter_chart data[:scatter_chart_data], xtitle: '学習時間（分）', ytitle: '達成率 (%)', suffix: '%', height: '400px' %>
        </div>
      </div>
    <% end %>
  </div>
</div>