config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root 'tops#index'

  get 'terms_of_service', to: 'terms_of_service#show'
  get 'privacy_policy', to: 'privacy_policy#show'

  # システム管理者用画面
  namespace :admin, path: 'aaaaaaaa' do
    root to: 'schools#index', as: 'root'

    devise_for :admins,
               only: %i[session password],
               controllers: { passwords: 'admins/passwords',
                              sessions: 'admins/sessions' }
    resources :schools do
      resources :teachers, param: :code, only: %i[show new create edit update]
    end
  end

  #++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
  # マルチテナントの切り分け
  scope '/:school_code' do
    #++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    # 教師用画面
    namespace :teacher, path: 't' do
      root to: 'students#index', as: 'root'

      devise_for :teachers,
                 only: %i[session password],
                 controllers: { passwords: 'teachers/passwords',
                                sessions: 'teachers/sessions' }
                                
      resources :students, only: %i[index edit update show destroy]
      resources :test_results, only: %i[index edit update show destroy] do
        collection do
          get :subject_achievement_rate
        end
      end
    end

    # 生徒用画面
    scope module: :student do
      root to: 'test_results#index', as: 'student_root'

      devise_for :students,
                 only: %i[session password registration confirmation],
                 controllers: { passwords: 'students/passwords',
                                sessions: 'students/sessions',
                                registrations: 'students/registrations',
                                confirmations: 'students/confirmations' }
      resources :test_results, except: [:show] do
        collection do
          get :subject_achievement_rate
        end
      end
    end
  end
end

app/views/shared/_admin_header.html.erb
<header class="header navbar navbar-expand-lg bg-light shadow-sm fixed-top">
  <div class="container px-0">
    <a href="index.html" class="navbar-brand pe-3">
      <%= link_to root_path, class: "navbar-brand pe-3" do %>
        Learning Mate
      <% end %>
    </a>
    <div id="navbarNav" class="offcanvas offcanvas-end">
      <div class="offcanvas-header border-top">
        <%= link_to (t 'defaults.logout'), destroy_admin_admin_session_path, class: 'btn btn-primary btn-sm fs-sm rounded d-none d-lg-inline-flex', data: {turbo_method: :delete} %>
      </div>      
    </div>

    <div class="form-check from-switch mode-switch pe-lg-1 ms-auto me-0" data-bs-toggle="mode">
      <div class="dropdown">
        <button class="btn btn-primary dropdown-toggle btn-sm" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false">
          学校を登録する
        </button>
        <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
          <li><%= link_to '学校一覧', admin_schools_path, class: 'dropdown-item' %></li>
          <li><%= link_to '学校を登録', new_admin_school_path, class: 'dropdown-item' %></li>
        </ul>
      </div>
    </div>

    <div class="form-check from-switch mode-switch pe-lg-1 ms-auto me-0" data-bs-toggle="mode">
      <%= link_to (t 'defaults.logout'), destroy_admin_admin_session_path, class: 'btn btn-primary btn-sm fs-sm rounded d-none d-lg-inline-flex', data: {turbo_method: :delete} %>
    </div>
  </div>
</header>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_messages" class="alert alert-danger">
    <ul class="mb-0">
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/shared/_footer.html.erb
<!-- Footer -->
<footer class="footer pt-5 pb-4 pb-lg-5">
  <div class="container pt-lg-4">
    <div class="row pb-5">
      <div class="col-lg-4 col-md-6">
        <div class="navbar-brand text-dark p-0 me-0 mb-3 mb-lg-4">
          <h3>Learning Mate</h3>
        </div>
      </div>
      <div class="col-xl-6 col-lg-7 col-md-5 offset-xl-2 offset-md-1 pt-4 pt-md-1 pt-lg-0">
        <div id="footer-links" class="row">
          <div class="col-lg-4">
            <h6 class="mb-2">
            <a href="#useful-links" class="d-block text-dark dropdown-toggle d-lg-none py-2" data-bs-toggle="collapse">Useful Links</a>
            </h6>
            <div id="useful-links" class="collapse d-lg-block" data-bs-parent="#footer-links">
              <ul class="nav flex-column mb-2 mb-lg-0">
                <li class="nav-item"><a href="<%=terms_of_service_path %>", class="nav-link d-inline-block px-0 pt-1 pb-2">Terms &amp; Conditions</a></li>
                <li class="nav-item"><a href="<%=privacy_policy_path %>", class="nav-link d-inline-block px-0 pt-1 pb-2">Privacy Policy</a></li>
              </ul>
            </div>
          </div>
          <div class="col-xl-4 col-lg-5 pt-2 pt-lg-0">
            <h6 class="mb-2">Contact</h6>
            <a href="https://forms.gle/NaBSGqofxi3guzEAA" target="_blank">お問い合わせはこちらから</a>
          </div>
        </div>
      </div>
    </div>
    <p class="nav d-block fs-xs text-center text-md-start pb-2 pb-lg-0 mb-0">
      &copy; All rights reserved. Made by Shimosako
  </div>
</footer>

app/views/shared/_header.html.erb
<!-- Navbar -->
<!-- Remove "fixed-top" class to make navigation bar scrollable with the page -->
<header class="header navbar navbar-expand-lg bg-light shadow-sm fixed-top">
  <div class="container px-0">
    <a href="index.html" class="navbar-brand pe-3">
      Learning Mate
    </a>
  </div>
</header>

app/views/shared/_student_header.html.erb
<header class="header navbar navbar-expand-lg bg-light shadow-sm fixed-top">
  <div class="container px-0">
    <a href="index.html" class="navbar-brand pe-3">
      <%= link_to root_path, class: "navbar-brand pe-3" do %>
        Learning Mate
      <% end %>
    </a>
    <div id="navbarNav" class="offcanvas offcanvas-end">
      <div class="offcanvas-header border-top">
        <%= link_to (t 'defaults.logout'), destroy_student_session_path, class: 'btn btn-primary btn-sm fs-sm rounded d-none d-lg-inline-flex', data: {turbo_method: :delete} %>
      </div>      
    </div>

    <div class="form-check from-switch mode-switch pe-lg-1 ms-auto me-0" data-bs-toggle="mode">
      <div class="dropdown">
        <button class="btn btn-primary dropdown-toggle btn-sm" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false">
          テストを登録する
        </button>
        <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
          <li><%= link_to 'テスト一覧', test_results_path, class: 'dropdown-item' %></li>
          <li><%= link_to 'テストを作成する', new_test_result_path, class: 'dropdown-item' %></li>
          <li><%= link_to 'グラフで見る', subject_achievement_rate_test_results_path, class: 'dropdown-item' %></li>
        </ul>
      </div>
    </div>

    <div class="form-check from-switch mode-switch pe-lg-1 ms-auto me-0" data-bs-toggle="mode">
      <%= link_to (t 'defaults.logout'), destroy_student_session_path, class: 'btn btn-primary btn-sm fs-sm rounded d-none d-lg-inline-flex', data: {turbo_method: :delete} %>
    </div>
  </div>
</header>

app/views/shared/_teacher_header.html.erb
<header class="header navbar navbar-expand-lg bg-light shadow-sm fixed-top">
  <div class="container px-0">
    <a href="index.html" class="navbar-brand pe-3">
      <%= link_to root_path, class: "navbar-brand pe-3" do %>
        Learning Mate
      <% end %>
    </a>
    <div id="navbarNav" class="offcanvas offcanvas-end">
      <div class="offcanvas-header border-top">
        <%= link_to (t 'defaults.logout'), destroy_teacher_teacher_session_path, class: 'btn btn-primary btn-sm fs-sm rounded d-none d-lg-inline-flex', data: {turbo_method: :delete} %>
      </div>      
    </div>

    <div class="form-check from-switch mode-switch pe-lg-1 ms-auto me-0" data-bs-toggle="mode">
      <%= link_to '生徒一覧', teacher_students_path, class: 'btn btn-primary btn-sm fs-sm rounded d-none d-lg-inline-flex' %>
    </div>

    <div class="form-check from-switch mode-switch pe-lg-1 ms-auto me-0" data-bs-toggle="mode">
      <%= link_to 'テスト結果一覧', teacher_test_results_path, class: 'btn btn-primary btn-sm fs-sm rounded d-none d-lg-inline-flex' %>
    </div>

    <div class="form-check from-switch mode-switch pe-lg-1 ms-auto me-0" data-bs-toggle="mode">
      <%= link_to (t 'defaults.logout'), destroy_teacher_teacher_session_path, class: 'btn btn-primary btn-sm fs-sm rounded d-none d-lg-inline-flex', data: {turbo_method: :delete} %>
    </div>
  </div>
</header>