config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root 'tops#index'

  get 'terms_of_service', to: 'terms_of_service#show'
  get 'privacy_policy', to: 'privacy_policy#show'

  # システム管理者用画面
  namespace :admin, path: 'aaaaaaaa' do
    root to: 'schools#index', as: 'root'

    devise_for :admins,
               only: %i[session password],
               controllers: { passwords: 'admins/passwords',
                              sessions: 'admins/sessions' }
    resources :schools do
      resources :teachers, param: :code, only: %i[show new create edit update]
    end
  end

  #++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
  # マルチテナントの切り分け
  scope '/:school_code' do
    #++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    # 教師用画面
    namespace :teacher, path: 't' do
      root to: 'students#index', as: 'root'

      devise_for :teachers,
                 only: %i[session password],
                 controllers: { passwords: 'teachers/passwords',
                                sessions: 'teachers/sessions' }
                                
      resources :students, only: %i[index edit update show destroy]
      resources :test_results, only: %i[index edit update show destroy] do
        collection do
          get :subject_achievement_rate
        end
      end
    end

    # 生徒用画面
    scope module: :student do
      root to: 'test_results#index', as: 'student_root'

      devise_for :students,
                 only: %i[session password registration confirmation],
                 controllers: { passwords: 'students/passwords',
                                sessions: 'students/sessions',
                                registrations: 'students/registrations',
                                confirmations: 'students/confirmations' }
      resources :test_results, except: [:show] do
        collection do
          get :subject_achievement_rate
        end
      end
    end
  end
end

app/models/school.rb
class School < ApplicationRecord
  before_validation :generate_unique_code, on: :create

  has_many :teachers, dependent: :destroy
  has_many :students, dependent: :destroy

  validates :name, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true, format: { with: /\A\d{10,11}\z/}
  validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP}
  validates :website, format: { with: URI::DEFAULT_PARSER.make_regexp}, allow_blank: true

  validates :code, presence: true, uniqueness: true

  def generate_unique_code
    loop do
      self.code = SecureRandom.hex(4)
      break unless School.exists?(code: code)
    end
  end

  def self.ransackable_attributes(auth_object = nil)
    ["address", "code", "created_at", "email", "id", "id_value", "name", "phone_number", "updated_at", "website"]
  end
end

app/controllers/admin/schools_controller.rb
class Admin::SchoolsController < Admin::BaseController
  before_action :set_school, only: [:show, :edit, :update, :destroy]

  def index
    @q = School.ransack(params[:q])
    @schools = @q.result(distinct: true).order(created_at: :asc)
  end
    
  # 新しい学校を作成するためのフォームを表示するアクション
  def new
    @school = School.new
    @school.generate_unique_code
  end
    
  # 新しい学校を作成するアクション
  def create
    @school = School.new(school_params)
    if @school.save
      redirect_to admin_schools_path, success: t('defaults.message.created', item: School.model_name.human)
    else
      flash.now['danger'] = t('defaults.message.not_created', item: School.model_name.human)
      render :new, status: :unprocessable_entity
    end
  end
    
  # 学校の詳細を表示するアクション
  def show
  end
    
  # 学校を編集するためのフォームを表示するアクション
  def edit
  end
    
  # 学校を更新するアクション
  def update
    if @school.update(school_params)
      redirect_to admin_school_path(@school), success: t('defaults.message.updated', item: School.model_name.human)
    else
      flash.now['danger'] = t('defaults.message.not_updated', item: School.model_name.human)
      render :edit, status: :unprocessable_entity
    end
  end
    
  # 学校を削除するアクション
  def destroy
    @school.destroy
    redirect_to admin_schools_path, success: t('defaults.message.deleted', item: School.model_name.human)
  end
    
  private

  def set_school
    @school = School.find(params[:id])
  end
    
  def school_params
    params.require(:school).permit(:name, :address, :phone_number, :email, :website)
  end
end

app/views/admin/schools/edit.html.erb
<% content_for(:title, t('.title')) %>
<!-- Sign up form -->
<div class="container d-flex flex-wrap justify-content-center justify-content-center pt-5">
  <div class="w-100 align-self-end pt-1 pt-md-4 pb-4" style="max-width: 526px;">
    <h1 class="text-center text-xl-start"><%= t '.title' %></h1>
    <%= form_with model: @school, url: admin_school_path(@school), local: true do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <div class="row">
        <div class="col-12">
          <div class="position-relative mb-4">
            <div class="form-group">
              <%= f.label :name %>
              <%= f.text_field :name, class: 'form-control' %>
            </div>
          </div>
        </div>
        <div class="col-12">
          <div class="position-relative mb-4">
            <div class="form-group">
              <%= f.label :address %>
              <%= f.text_field :address, class: 'form-control' %>
            </div>
          </div>
        </div>
        <div class="col-12">
          <div class="position-relative mb-4">
            <div class="form-group">
              <%= f.label :phone_number %>
              <%= f.text_field :phone_number, class: 'form-control' %>
            </div>
          </div>
        </div>
        <div class="col-12">
          <div class="position-relative mb-4">
            <div class="form-group">
              <%= f.label :email %>
              <%= f.text_field :email, class: 'form-control' %>
            </div>
          </div>
        </div>
        <div class="col-12">
          <div class="position-relative mb-4">
            <div class="form-group">
              <%= f.label :website %>
              <%= f.text_field :website, class: 'form-control' %>
            </div>
          </div>
        </div>
      </div>
      <%= f.submit '新規登録', class: "btn btn-primary shadow-primary btn-lg w-100" %>
    <% end %>
  </div>
</div>

app/views/admin/schools/index.html.erb
<% content_for(:title, t('.title')) %>
<!-- Breadcrumb -->
<nav class="container mt-lg-4 pt-5" aria-label="breadcrumb"></nav>
<!-- Page content -->
<section class="container mt-4 mb-lg-5 pt-lg-2 pb-5">
  <!-- Page title + Layout switcher + Search form -->
  <div class="row align-items-end gy-3 mb-4 pb-lg-3 pb-1">
    <div class="col-lg-5 col-md-4">
      <h1 class="mb-2 mb-md-0"><%= t '.title' %></h1>
    </div>
    <div class="col-lg-7 col-md-8 d-flex justify-content-end">
      <%= search_form_for @q, url: admin_schools_path do |f| %>
        <div class="row align-items-end">
          <div class="col-lg-7 col-md-6 col-sm-6 mb-2">
            <div class="input-group">
              <%= f.search_field :name_cont, class: 'form-control', placeholder: '学校を検索' %>
            </div>
          </div>
          <div class="col-lg-2 col-md-4 col-sm-6 mb-2">
            <div class="input-group">
              <%= f.submit "検索", class: 'btn btn-primary' %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <table class="table table-striped">
        <thead>
        <tr>
          <th>学校名</th>
          <th>住所</th>
          <th>電話番号</th>
          <th>メールアドレス</th>
          <th>Webサイト</th>
          <th></th>
        </tr>
        </thead>
        <tbody>
          <% @schools.each do |school| %>
            <tr>
              <td><%= school.name %></td>
              <td><%= school.address %></td>
              <td><%= school.phone_number %></td>
              <td><%= school.email %></td>
              <td><%= school.website %></td>
              <td>
                <div class="btn-group" role="group">
                  <%= link_to t('defaults.show'), admin_school_path(school), class: 'btn btn-info me-2' %>
                  <%= link_to t('defaults.edit'), edit_admin_school_path(school), class: 'btn btn-success me-2' %>
                  <%= button_to t('defaults.delete'), admin_school_path(school), method: :delete, data: { turbo_confirm: "本当に削除しますか？" }, class: 'btn btn-danger' %>
                </div>  
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</section>

app/views/admin/schools/new.html.erb
<% content_for(:title, t('.title')) %>
<!-- Sign up form -->
<div class="container d-flex flex-wrap justify-content-center justify-content-center pt-5">
  <div class="w-100 align-self-end pt-1 pt-md-4 pb-4" style="max-width: 526px;">
    <h1 class="text-center text-xl-start"><%= t '.title' %></h1>
    <%= form_with(model: @school, url: admin_schools_path) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <div class="row">
        <div class="col-12">
          <div class="position-relative mb-4">
            <div class="form-group">
              <%= f.label :name %>
              <%= f.text_field :name, class: 'form-control' %>
            </div>
          </div>
        </div>
        <div class="col-12">
          <div class="position-relative mb-4">
            <div class="form-group">
              <%= f.label :address %>
              <%= f.text_field :address, class: 'form-control' %>
            </div>
          </div>
        </div>
        <div class="col-12">
          <div class="position-relative mb-4">
            <div class="form-group">
              <%= f.label :phone_number %>
              <%= f.text_field :phone_number, class: 'form-control' %>
            </div>
          </div>
        </div>
        <div class="col-12">
          <div class="position-relative mb-4">
            <div class="form-group">
              <%= f.label :email %>
              <%= f.text_field :email, class: 'form-control' %>
            </div>
          </div>
        </div>
        <div class="col-12">
          <div class="position-relative mb-4">
            <div class="form-group">
              <%= f.label :website %>
              <%= f.text_field :website, class: 'form-control' %>
            </div>
          </div>
        </div>
      </div>
      <%= f.submit '新規登録', class: "btn btn-primary shadow-primary btn-lg w-100" %>
    <% end %>
  </div>
</div>

app/views/admin/schools/show.html.erb
<% content_for(:title, t('.title')) %>
<!-- Breadcrumb -->
<nav class="container mt-lg-4 pt-5" aria-label="breadcrumb"></nav>
<!-- Page content -->
<section class="container mt-4 mb-lg-5 pt-lg-2 pb-5">
  <!-- Page title + Layout switcher + Search form -->
  <div class="row align-items-end gy-3 mb-4 pb-lg-3 pb-1">
    <div class="col-lg-5 col-md-4">
      <h1 class="mb-2 mb-md-0"><%= t '.title' %></h1>
    </div>
  </div>
  <div class="btn-group mb-3" role="group">
    <%= link_to t('defaults.edit'), edit_admin_school_path(@school), class: 'btn btn-success me-2' %>
    <%= button_to t('defaults.delete'), admin_school_path(@school), method: :delete, data: { turbo_confirm: "本当に削除しますか？" }, class: 'btn btn-danger me-2' %>
    <%= link_to '先生を追加する', new_admin_school_teacher_path(@school), class: 'btn btn-primary me-2' %>
    <%= link_to '学校一覧ページへ', admin_schools_path, class: 'btn btn-secondary' %>
  </div>
  <div class="row">
    <div class="col-md-12">
      <table class="table table-striped">
        <thead>
        <tr>
          <th><%= School.human_attribute_name(:name) %></th>
          <th>コード</th>
          <th><%= School.human_attribute_name(:address) %></th>
          <th><%= School.human_attribute_name(:phone_number)%></th>
          <th><%= School.human_attribute_name(:email)%></th>
          <th><%= School.human_attribute_name(:website) %></th>
          <th>先生一覧</th>
        </tr>
        </thead>
        <tbody>
          <td><%= @school.name %></td>
          <td><%= @school.code %></td>
          <td><%= @school.address %></td>
          <td><%= @school.phone_number %></td>
          <td><%= @school.email %></td>
          <td><%= @school.website %></td>
          <td>
            <% @school.teachers.each do |teacher| %>
              <%= link_to teacher.name, admin_school_teacher_path(@school, teacher) %><br>
            <% end %>
          </td>
        </tbody>
      </table>
    </div>
  </div>
</section>